name: flutter_infinite_list
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  stream_transform: ^2.0.0
  dio: ^4.0.4
  retrofit: ^3.0.1
  freezed_annotation: ^1.0.0
  loggy: ^2.0.1
  flutter_loggy: ^2.0.1
  flutter_loggy_dio: ^2.0.0+3
  json_serializable: ^6.1.3
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  mocktail: ^0.2.0
  flutter_lints: ^1.0.4
  retrofit_generator: ^3.0.1+1
  build_runner: ^2.1.7
  freezed: ^1.0.2+1

flutter:
  uses-material-design: true
